const GET_CURRENCY_LIST = 'GET_CURRENCY_LIST';
const GET_CURRENCY_LIST_SUCCESS = 'GET_CURRENCY_LIST_SUCCESS';
const GET_CURRENCY_LIST_ERROR = 'GET_CURRENCY_LIST_ERROR';
const DELETE_CURRENCY = 'DELETE_CURRENCY';
const DELETE_CURRENCY_SUCCESS = 'DELETE_CURRENCY_SUCCESS';

export {
  GET_CURRENCY_LIST,
  GET_CURRENCY_LIST_SUCCESS,
  GET_CURRENCY_LIST_ERROR,
  DELETE_CURRENCY,
  DELETE_CURRENCY_SUCCESS,
};
